// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UroCommand.proto

package com.example.uropatruljen_app.protobuf;

public interface ClientOrBuilder extends
    // @@protoc_insertion_point(interface_extends:uropatruljen_app.Client)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string token = 1;</code>
   * @return Whether the token field is set.
   */
  boolean hasToken();
  /**
   * <code>optional string token = 1;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>optional string token = 1;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>optional string imei = 2;</code>
   * @return Whether the imei field is set.
   */
  boolean hasImei();
  /**
   * <code>optional string imei = 2;</code>
   * @return The imei.
   */
  java.lang.String getImei();
  /**
   * <code>optional string imei = 2;</code>
   * @return The bytes for imei.
   */
  com.google.protobuf.ByteString
      getImeiBytes();
}
