// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UroCommand.proto

package com.example.uropatruljen_app.protobuf;

public interface CommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:uropatruljen_app.Command)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string command = 1;</code>
   * @return Whether the command field is set.
   */
  boolean hasCommand();
  /**
   * <code>optional string command = 1;</code>
   * @return The command.
   */
  java.lang.String getCommand();
  /**
   * <code>optional string command = 1;</code>
   * @return The bytes for command.
   */
  com.google.protobuf.ByteString
      getCommandBytes();

  /**
   * <code>.uropatruljen_app.Client client = 2;</code>
   * @return Whether the client field is set.
   */
  boolean hasClient();
  /**
   * <code>.uropatruljen_app.Client client = 2;</code>
   * @return The client.
   */
  com.example.uropatruljen_app.protobuf.Client getClient();
  /**
   * <code>.uropatruljen_app.Client client = 2;</code>
   */
  com.example.uropatruljen_app.protobuf.ClientOrBuilder getClientOrBuilder();

  /**
   * <code>.uropatruljen_app.Music music = 3;</code>
   * @return Whether the music field is set.
   */
  boolean hasMusic();
  /**
   * <code>.uropatruljen_app.Music music = 3;</code>
   * @return The music.
   */
  com.example.uropatruljen_app.protobuf.Music getMusic();
  /**
   * <code>.uropatruljen_app.Music music = 3;</code>
   */
  com.example.uropatruljen_app.protobuf.MusicOrBuilder getMusicOrBuilder();

  /**
   * <code>.uropatruljen_app.Light light = 4;</code>
   * @return Whether the light field is set.
   */
  boolean hasLight();
  /**
   * <code>.uropatruljen_app.Light light = 4;</code>
   * @return The light.
   */
  com.example.uropatruljen_app.protobuf.Light getLight();
  /**
   * <code>.uropatruljen_app.Light light = 4;</code>
   */
  com.example.uropatruljen_app.protobuf.LightOrBuilder getLightOrBuilder();

  /**
   * <code>.uropatruljen_app.Uro uro = 5;</code>
   * @return Whether the uro field is set.
   */
  boolean hasUro();
  /**
   * <code>.uropatruljen_app.Uro uro = 5;</code>
   * @return The uro.
   */
  com.example.uropatruljen_app.protobuf.Uro getUro();
  /**
   * <code>.uropatruljen_app.Uro uro = 5;</code>
   */
  com.example.uropatruljen_app.protobuf.UroOrBuilder getUroOrBuilder();

  /**
   * <code>.uropatruljen_app.NetworkCre network = 6;</code>
   * @return Whether the network field is set.
   */
  boolean hasNetwork();
  /**
   * <code>.uropatruljen_app.NetworkCre network = 6;</code>
   * @return The network.
   */
  com.example.uropatruljen_app.protobuf.NetworkCre getNetwork();
  /**
   * <code>.uropatruljen_app.NetworkCre network = 6;</code>
   */
  com.example.uropatruljen_app.protobuf.NetworkCreOrBuilder getNetworkOrBuilder();

  public com.example.uropatruljen_app.protobuf.Command.MsgCase getMsgCase();
}
