// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UroCommand.proto

package com.example.uropatruljen_app.protobuf;

public interface LightOrBuilder extends
    // @@protoc_insertion_point(interface_extends:uropatruljen_app.Light)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool state = 1;</code>
   * @return Whether the state field is set.
   */
  boolean hasState();
  /**
   * <code>optional bool state = 1;</code>
   * @return The state.
   */
  boolean getState();

  /**
   * <code>optional int32 red = 2;</code>
   * @return Whether the red field is set.
   */
  boolean hasRed();
  /**
   * <code>optional int32 red = 2;</code>
   * @return The red.
   */
  int getRed();

  /**
   * <code>optional int32 green = 3;</code>
   * @return Whether the green field is set.
   */
  boolean hasGreen();
  /**
   * <code>optional int32 green = 3;</code>
   * @return The green.
   */
  int getGreen();

  /**
   * <code>optional int32 blue = 4;</code>
   * @return Whether the blue field is set.
   */
  boolean hasBlue();
  /**
   * <code>optional int32 blue = 4;</code>
   * @return The blue.
   */
  int getBlue();
}
