// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UroCommand.proto

package com.example.uropatruljen_app.protobuf;

public interface NetworkCreOrBuilder extends
    // @@protoc_insertion_point(interface_extends:uropatruljen_app.NetworkCre)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string ssid = 1;</code>
   * @return Whether the ssid field is set.
   */
  boolean hasSsid();
  /**
   * <code>optional string ssid = 1;</code>
   * @return The ssid.
   */
  java.lang.String getSsid();
  /**
   * <code>optional string ssid = 1;</code>
   * @return The bytes for ssid.
   */
  com.google.protobuf.ByteString
      getSsidBytes();

  /**
   * <code>optional string psw = 2;</code>
   * @return Whether the psw field is set.
   */
  boolean hasPsw();
  /**
   * <code>optional string psw = 2;</code>
   * @return The psw.
   */
  java.lang.String getPsw();
  /**
   * <code>optional string psw = 2;</code>
   * @return The bytes for psw.
   */
  com.google.protobuf.ByteString
      getPswBytes();
}
