// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UroCommand.proto

package com.example.uropatruljen_app.protobuf;

public interface NetworkCreOrBuilder extends
    // @@protoc_insertion_point(interface_extends:uropatruljen_app.NetworkCre)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string ssid = 1;</code>
   * @return Whether the ssid field is set.
   */
  boolean hasSsid();
  /**
   * <code>optional string ssid = 1;</code>
   * @return The ssid.
   */
  java.lang.String getSsid();
  /**
   * <code>optional string ssid = 1;</code>
   * @return The bytes for ssid.
   */
  com.google.protobuf.ByteString
      getSsidBytes();

  /**
   * <code>optional string pass = 2;</code>
   * @return Whether the pass field is set.
   */
  boolean hasPass();
  /**
   * <code>optional string pass = 2;</code>
   * @return The pass.
   */
  java.lang.String getPass();
  /**
   * <code>optional string pass = 2;</code>
   * @return The bytes for pass.
   */
  com.google.protobuf.ByteString
      getPassBytes();
}
