// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UroCommand.proto

package com.example.uropatruljen_app.protobuf;

public interface UroOrBuilder extends
    // @@protoc_insertion_point(interface_extends:uropatruljen_app.Uro)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string model = 1;</code>
   * @return Whether the model field is set.
   */
  boolean hasModel();
  /**
   * <code>optional string model = 1;</code>
   * @return The model.
   */
  java.lang.String getModel();
  /**
   * <code>optional string model = 1;</code>
   * @return The bytes for model.
   */
  com.google.protobuf.ByteString
      getModelBytes();
}
